const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Scheme = require('../models/Scheme');

dotenv.config();

// Comprehensive database of 32+ Indian Legal Aid and Central/State Welfare Schemes
const schemes = [
    // ================= 1. LEGAL AID & ACCESS TO JUSTICE =================
    {
        name: 'NALSA Free Legal Aid & Representation Scheme',
        description: 'Statutory free legal assistance, court fee waiver, and senior advocate representation under Section 12 of the Legal Services Authorities Act, 1987.',
        categoryTag: 'Legal Aid',
        ministry: 'National Legal Services Authority (Ministry of Law and Justice)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '100% Free Legal Counsel & Court Fee Exemption',
        helpline: '15100 (National Legal Aid Toll Free)',
        benefits: [
            'Payment of court fees, process fees, and other litigation charges',
            'Free assignment of Legal Aid Advocate or Senior Counsel',
            'Free certified copies of judgments and court transcripts',
            'Pre-litigation conciliation and Lok Adalat dispute settlement',
        ],
        eligibility: {
            ageMin: 0,
            ageMax: null,
            incomeMax: 300000, // Standard ceiling for general category; waived for women, SC/ST, custody
            gender: 'All',
            occupation: [],
            education: [],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isDisability: true,
            isBelowPovertyLine: true,
        },
        requiredDocuments: [
            'Aadhaar / Photo ID Proof',
            'Income Certificate (if applicable - waived for SC/ST/Women/Custody cases)',
            'Case Documents / Copy of Police Complaint / Notice received',
        ],
        applicationProcess: [
            'Submit application at nearest Taluk / District Legal Services Authority (DLSA) or online via nalsa.gov.in',
            'Front Office Member scrutinizes legal merit and prima facie urgency within 48 hours',
            'Panel Lawyer is assigned and legal consultation commences',
            'Legal Aid Advocate drafts petition / defends proceedings in court',
        ],
        officialUrl: 'https://nalsa.gov.in',
        tags: ['legal aid', 'nalsa', 'lawyer', 'free legal counsel', 'court fee', 'dlsa', 'lok adalat'],
    },
    {
        name: 'Tele-Law: Mainstreaming Legal Advice to Rural Masses',
        description: 'Direct video/voice consultation with High Court & Supreme Court panel lawyers via Common Service Centres (CSCs) or the Tele-Law Citizen Mobile App.',
        categoryTag: 'Legal Aid',
        ministry: 'Ministry of Law and Justice',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Free Pre-litigation Legal Advice & Mediation Guidance',
        helpline: '14430 / Tele-Law Helpline',
        benefits: [
            'Instant video-conference consultation with registered panel advocates',
            'Pre-litigation legal advice preventing unnecessary court litigation',
            'Available in 22 official Indian languages at gram panchayat CSCs',
            'Case escalation to DLSA for free courtroom representation if needed',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: ['Rural worker', 'Farmer', 'Self-employed', 'Student', 'Unemployed'],
            education: [],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isRural: true,
            isFarmer: true,
            isBelowPovertyLine: true,
        },
        requiredDocuments: [
            'Aadhaar Card / Mobile Number for OTP',
            'Brief summary notes or notices received regarding dispute',
        ],
        applicationProcess: [
            'Visit the nearest Village Common Service Centre (CSC) or download Tele-Law App',
            'Select legal query domain (Family, Land, Labour, Criminal, Consumer)',
            'Book convenient video/audio consultation slot with panel lawyer',
            'Receive digital advice certificate and follow-up guidance',
        ],
        officialUrl: 'https://tele-law.in',
        tags: ['tele-law', 'rural legal advice', 'csc', 'lawyer consultation', 'panchayat'],
    },
    {
        name: 'Nyaya Bandhu (Pro Bono Legal Services)',
        description: 'Connects marginalized litigants with registered pro bono practicing advocates for dedicated court representation across High Courts and Supreme Court.',
        categoryTag: 'Legal Aid',
        ministry: 'Department of Justice (Ministry of Law and Justice)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Pro Bono (Free) Senior Advocate Court Representation',
        helpline: '011-23383637',
        benefits: [
            'Direct assignment of practicing pro bono advocates',
            'Representation across High Courts, Supreme Court, and Central Administrative Tribunals',
            'End-to-end petition drafting, filing, and oral arguments',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: 300000,
            gender: 'All',
            occupation: [],
            education: [],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isBelowPovertyLine: true,
            isDisability: true,
        },
        requiredDocuments: [
            'Aadhaar Card',
            'Income & Caste Certificate',
            'Case History & Impugned Orders (if appealing)',
        ],
        applicationProcess: [
            'Download Nyaya Bandhu Android/iOS App or visit portal',
            'Register with mobile number and upload case summary',
            'Case matched with registered pro bono advocate based on jurisdiction',
            'Advocate accepts case and manages courtroom representation',
        ],
        officialUrl: 'https://www.probono-doj.in',
        tags: ['nyaya bandhu', 'pro bono', 'supreme court', 'high court', 'free lawyer'],
    },
    {
        name: 'DISHA: Designing Innovative Solutions for Holistic Access to Justice',
        description: 'Pan-India comprehensive access-to-justice initiative consolidating Tele-Law, Nyaya Bandhu, and legal literacy campaigns into a unified citizen-facing legal protection net.',
        categoryTag: 'Legal Aid',
        ministry: 'Department of Justice (Ministry of Law and Justice)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Free Citizen Legal Empowerment & Pre-Litigation Conflict Resolution',
        helpline: '1800-11-2555',
        benefits: [
            'Empowerment through Gram Nyayalaya legal dispute resolution',
            'Legal aid clinics at grassroots Village Knowledge Centres',
            'Direct linkage with dispute resolution Lok Adalats',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: [],
            education: [],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isRural: true,
            isBelowPovertyLine: true,
        },
        requiredDocuments: ['Aadhaar Card', 'Grievance / Dispute Summary'],
        applicationProcess: [
            'Access justice portal via disha.doj.gov.in or local Legal Aid Clinic',
            'Register citizen dispute profile',
            'Receive dispute counseling and pre-litigation resolution track',
        ],
        officialUrl: 'https://doj.gov.in/disha-scheme',
        tags: ['disha', 'access to justice', 'legal clinics', 'gram nyayalaya'],
    },

    // ================= 2. AGRICULTURE & RURAL DEVELOPMENT =================
    {
        name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
        description: 'Central sector scheme with 100% funding from Government of India providing income support of ₹6,000 annually in three equal installments to all landholding farmer families.',
        categoryTag: 'Agriculture',
        ministry: 'Ministry of Agriculture and Farmers Welfare',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '₹6,000 per year in 3 direct bank transfers',
        helpline: '155261 / 011-24300606',
        benefits: [
            'Direct Benefit Transfer (DBT) of ₹2,000 every four months',
            'Directly transferred to Aadhaar-seeded bank account with zero middlemen',
            'Supplementary financial security for seeds, fertilizers, and inputs',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: ['Farmer', 'Agriculturalist'],
            education: [],
            category: [],
            isFarmer: true,
        },
        requiredDocuments: [
            'Aadhaar Card',
            'Land Ownership Title (Pattadar Passbook / RoR 1B)',
            'Active Bank Passbook seeded with NPCI / Aadhaar',
        ],
        applicationProcess: [
            'Register on Farmers Corner on pmkisan.gov.in or through local Patwari / CSC',
            'Enter Aadhaar, Land Details, and Bank Account',
            'Complete Aadhaar e-KYC via facial or OTP verification',
            'Verification by State Nodal Officer followed by DBT fund release',
        ],
        officialUrl: 'https://pmkisan.gov.in',
        tags: ['farmer', 'pm-kisan', 'agriculture', 'dbt', 'crop investment'],
    },
    {
        name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
        description: 'Comprehensive crop insurance against non-preventable natural risks (drought, flood, unseasonal rains, pest infestation) with minimal premium rates (1.5% - 2%).',
        categoryTag: 'Agriculture',
        ministry: 'Ministry of Agriculture and Farmers Welfare',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Up to 100% Crop Value Insurance Coverage against Yield Loss',
        helpline: '14447 / PMFBY Kisan Helpline',
        benefits: [
            'Uniform maximum premium of only 2% for Kharif, 1.5% for Rabi, and 5% for commercial crops',
            'Post-harvest loss assessment up to 14 days after crop cutting',
            'Instant claim intimation via Crop Insurance Mobile App within 72 hours',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: ['Farmer', 'Tenant Farmer', 'Sharecropper'],
            education: [],
            category: [],
            isFarmer: true,
        },
        requiredDocuments: [
            'Land Record (RoR / Khasra Khatauni / Sowing Certificate)',
            'Aadhaar Card',
            'Bank Passbook Details',
        ],
        applicationProcess: [
            'Enroll on pmfby.gov.in, nearest bank branch, or via CSC before seasonal cut-off date',
            'Submit land survey number and crop sown certificate',
            'In case of localized disaster, report claim within 72 hours on the mobile app',
        ],
        officialUrl: 'https://pmfby.gov.in',
        tags: ['crop insurance', 'fasal bima', 'pmfby', 'flood drought compensation'],
    },
    {
        name: 'Kisan Credit Card (KCC) Scheme',
        description: 'Institutional short-term credit facility for farmers at highly subsidized 4% effective interest rate with prompt repayment incentive for agricultural inputs and livestock.',
        categoryTag: 'Agriculture',
        ministry: 'Ministry of Agriculture / Department of Financial Services',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Subsidized Credit Limit up to ₹3,00,000 at 4% Interest',
        helpline: '1800-180-1551',
        benefits: [
            'Revolving cash credit facility valid for 5 years with annual review',
            '3% interest subvention for prompt repayment bringing effective interest to 4%',
            'Covers animal husbandry, dairy, fisheries, and post-harvest expenses',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: 75,
            incomeMax: null,
            gender: 'All',
            occupation: ['Farmer', 'Tenant Farmer', 'Dairy Farmer', 'Fisheries Worker'],
            education: [],
            category: [],
            isFarmer: true,
        },
        requiredDocuments: ['Aadhaar Card', 'Land Revenue Record / Lease Agreement', 'Passport Photographs'],
        applicationProcess: [
            'Fill single-page KCC application form at nearest commercial/cooperative bank branch',
            'Bank issues RuPay Kisan Credit Card within 14 business days',
            'Withdraw funds at ATMs or purchase seeds/fertilizer at PoS merchant machines',
        ],
        officialUrl: 'https://myscheme.gov.in/schemes/kcc',
        tags: ['kcc', 'kisan credit card', 'crop loan', 'low interest farm loan'],
    },
    {
        name: 'Telangana Rythu Bandhu / Rythu Bharosa',
        description: 'Flagship farmer investment support scheme by Government of Telangana providing ₹10,000 per acre per year for agriculture and horticulture crops.',
        categoryTag: 'Agriculture',
        ministry: 'Department of Agriculture, Government of Telangana',
        state: 'Telangana',
        isCentralScheme: false,
        financialBenefit: '₹10,000 per acre annually (Kharif & Rabi seasons)',
        helpline: '1800-425-4033',
        benefits: [
            'Direct seasonal investment support for seeds, fertilizer, field prep',
            'No upper ceiling on acreage ownership',
            'Direct credit to farmer bank account without loan deductions',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: ['Farmer'],
            education: [],
            category: [],
            isFarmer: true,
        },
        requiredDocuments: [
            'Pattadar Passbook / Dharani Land Record ID',
            'Aadhaar Card',
            'Bank Account Details',
        ],
        applicationProcess: [
            'Land ownership recorded in Dharani Portal database',
            'Agriculture Extension Officer (AEO) verifies field data',
            'Direct treasury transfer to verified farmer account each crop season',
        ],
        officialUrl: 'https://dharani.telangana.gov.in',
        tags: ['telangana', 'rythu bandhu', 'farmers', 'telangana schemes'],
    },

    // ================= 3. HEALTHCARE & MEDICAL WELFARE =================
    {
        name: 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)',
        description: 'World\'s largest government-funded health assurance scheme providing catastrophic health coverage up to ₹5 lakh per family per year.',
        categoryTag: 'Healthcare',
        ministry: 'National Health Authority (Ministry of Health & Family Welfare)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '₹5,00,000 / family / year for secondary & tertiary hospitalization',
        helpline: '14555 / 1800-111-565',
        benefits: [
            'Cashless and paperless access to services at 27,000+ empanelled hospitals',
            'Coverage for 1,949 medical and surgical procedures',
            'Pre and post hospitalization expenses for 15 days',
            'No restriction on family size, age, or gender',
        ],
        eligibility: {
            ageMin: null,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: [],
            education: [],
            category: ['SC', 'ST', 'OBC', 'EWS', 'General'],
            isBelowPovertyLine: true,
            isRural: true,
        },
        requiredDocuments: [
            'Aadhaar Card',
            'Ration Card / SECC Data Reference',
            'Mobile number linked to Aadhaar',
        ],
        applicationProcess: [
            'Verify eligibility on mera.pmjay.gov.in or at Ayushman Mitra counter in any hospital',
            'Complete e-KYC biometric verification with Aadhaar',
            'Instant issuance of Golden Ayushman Card',
            'Present card for cashless admission and treatment',
        ],
        officialUrl: 'https://pmjay.gov.in',
        tags: ['health insurance', 'ayushman bharat', 'hospital', 'cashless treatment', 'medical'],
    },
    {
        name: 'Pradhan Mantri Bharatiya Janaushadhi Pariyojana (PMBJP)',
        description: 'Provides quality generic medicines, surgical items, and nutraceuticals at 50% to 90% cheaper prices compared to branded market alternatives through Jan Aushadhi Kendras.',
        categoryTag: 'Healthcare',
        ministry: 'Department of Pharmaceuticals (Ministry of Chemicals and Fertilizers)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '50% - 90% Savings on Quality Prescription Medications',
        helpline: '1800-180-8080',
        benefits: [
            'Over 2,000 generic medicines and 300 surgical consumables available',
            'Jan Aushadhi Suvidha biodegradable sanitary pads for only ₹1 per pad',
            'Strict WHO-GMP certified laboratory quality testing',
        ],
        eligibility: {
            ageMin: 0,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: [],
            education: [],
            category: [],
        },
        requiredDocuments: ['Valid Doctor Prescription (Rx)'],
        applicationProcess: [
            'Locate nearest PMBJP Jan Aushadhi Kendra via \'Jan Aushadhi Sugam\' mobile app',
            'Present valid doctor prescription at the counter',
            'Purchase generic formulation at regulated MRP',
        ],
        officialUrl: 'https://janaushadhi.gov.in',
        tags: ['generic medicine', 'janaushadhi', 'cheap medicine', 'pharmacy'],
    },
    {
        name: 'Nikshay Poshan Yojana (Nutritional Support for TB Patients)',
        description: 'Direct Benefit Transfer (DBT) scheme providing ₹500 - ₹1,000 monthly financial nutrition support to all registered Tuberculosis patients throughout treatment duration.',
        categoryTag: 'Healthcare',
        ministry: 'Central TB Division (Ministry of Health and Family Welfare)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '₹500 to ₹1,000 monthly direct bank transfer during treatment',
        helpline: '1800-11-6666 (Nikshay Helpline)',
        benefits: [
            'Direct monthly nutritional grant transferred to patient account',
            'Free anti-TB medications and clinical follow-up tests',
            'Community volunteer support through Ni-kshay Mitra program',
        ],
        eligibility: {
            ageMin: 0,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: [],
            education: [],
            category: [],
        },
        requiredDocuments: ['Aadhaar Card', 'Nikshay Notification ID / Health Center Card', 'Bank Account Passbook'],
        applicationProcess: [
            'Get registered and diagnosed at any Government or Private Designated Microscopy Center',
            'Health worker generates unique Nikshay ID and links bank details',
            'Monthly nutritional aid credited via PFMS pipeline',
        ],
        officialUrl: 'https://nikshay.in',
        tags: ['tb nutrition', 'nikshay', 'health aid', 'dbt medical'],
    },

    // ================= 4. MSME, BUSINESS & ENTREPRENEURSHIP =================
    {
        name: 'PM Street Vendor\'s AtmaNirbhar Nidhi (PM SVANidhi)',
        description: 'Micro-credit collateral-free facility empowering street vendors with working capital loans starting from ₹10,000 up to ₹50,000 with 7% interest subsidy.',
        categoryTag: 'MSME & Business',
        ministry: 'Ministry of Housing and Urban Affairs',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Collateral-free loan up to ₹50,000 + 7% Interest Subsidy',
        helpline: '1800-11-1979',
        benefits: [
            'First tranche loan of ₹10,000, escalating to ₹20,000 and ₹50,000 on timely repayment',
            '7% annual interest subsidy credited directly to bank',
            'Cashback incentives up to ₹1,200/year on digital transactions',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: 65,
            incomeMax: null,
            gender: 'All',
            occupation: ['Street Vendor', 'Hawker', 'Artisan', 'Self-employed'],
            education: [],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isBelowPovertyLine: false,
        },
        requiredDocuments: [
            'Aadhaar Card',
            'Vending Certificate / Identity Card issued by Urban Local Body (ULB) / Letter of Recommendation',
            'Bank Account details',
        ],
        applicationProcess: [
            'Visit pmsvanidhi.mohua.gov.in or apply at municipal office / bank branch',
            'Provide Vending ID / ULB survey reference',
            'Select preferred lending institution (Public / Private Bank or MFI)',
            'Digital sanction and disbursal within 7 business days',
        ],
        officialUrl: 'https://pmsvanidhi.mohua.gov.in',
        tags: ['svanidhi', 'street vendor', 'micro loan', 'business loan', 'collateral free'],
    },
    {
        name: 'Pradhan Mantri MUDRA Yojana (PMMY)',
        description: 'Enables micro and small enterprises to access collateral-free institutional credit up to ₹10 Lakh in three tiers: Shishu, Kishor, and Tarun.',
        categoryTag: 'MSME & Business',
        ministry: 'Department of Financial Services (Ministry of Finance)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Collateral-free Loans up to ₹10,00,000 (Shishu, Kishor, Tarun)',
        helpline: '1800-180-1111',
        benefits: [
            'Shishu: Loans up to ₹50,000 for budding micro startups',
            'Kishor: Loans from ₹50,000 to ₹5,00,000 for scaling businesses',
            'Tarun: Loans from ₹5,00,000 to ₹10,00,000 for mature expansion',
            'No collateral or third-party security required',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: 65,
            incomeMax: null,
            gender: 'All',
            occupation: ['Entrepreneur', 'Trader', 'Artisan', 'Manufacturer', 'Self-employed'],
            education: [],
            category: [],
        },
        requiredDocuments: [
            'Identity & Residence Proof (Aadhaar, Voter ID, PAN)',
            'Business Profile / Project Report outlining estimated revenue & capital need',
            'Bank Account statements for past 6 months',
        ],
        applicationProcess: [
            'Apply through Udyamimitra portal (udyamimitra.in) or any scheduled commercial bank / NBFC',
            'Submit business proposal and quotation of machinery / working capital',
            'Bank processes sanction and issues MUDRA RuPay Card',
        ],
        officialUrl: 'https://www.mudra.org.in',
        tags: ['mudra', 'business loan', 'startup loan', 'shishu', 'tarun', 'msme'],
    },
    {
        name: 'Stand-Up India Scheme for Women & SC/ST Entrepreneurs',
        description: 'Bank loans between ₹10 Lakh and ₹1 Crore to at least one SC/ST and one Woman borrower per bank branch for setting up greenfield enterprises.',
        categoryTag: 'MSME & Business',
        ministry: 'Ministry of Finance',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Greenfield Enterprise Loans from ₹10 Lakh to ₹1 Crore',
        helpline: '1800-180-1111',
        benefits: [
            'Comprehensive composite loan covering 75% to 85% of project cost',
            'Handholding support through SIDBI and NABARD',
            'Tenure of repayment up to 7 years with 18 months moratorium',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            gender: 'Female', // Or SC/ST males
            occupation: ['Entrepreneur'],
            education: [],
            category: ['SC', 'ST', 'General', 'OBC', 'EWS'],
        },
        requiredDocuments: [
            'Identity & Address Proof',
            'Caste Certificate (if SC/ST)',
            'Detailed Project Report (DPR) for Greenfield venture',
            'Proof of registered manufacturing/service premises',
        ],
        applicationProcess: [
            'Register on standupmitra.in portal',
            'Choose handholding agency / nearest partner bank branch',
            'Submit DPR and environmental clearance (if manufacturing)',
            'Loan sanction and release in phased milestones',
        ],
        officialUrl: 'https://www.standupmitra.in',
        tags: ['women entrepreneur', 'sc st loan', 'stand up india', 'business grant'],
    },
    {
        name: 'Prime Minister\'s Employment Generation Programme (PMEGP)',
        description: 'Credit-linked subsidy program providing up to 35% capital subsidy for establishing micro-enterprises in manufacturing (up to ₹50 Lakh) and service sectors (up to ₹20 Lakh).',
        categoryTag: 'MSME & Business',
        ministry: 'Ministry of Micro, Small and Medium Enterprises (MSME)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '15% to 35% Margin Money Government Capital Subsidy',
        helpline: '1800-180-6763',
        benefits: [
            'Subsidy rate of 25% for urban and 35% for rural / special category beneficiaries',
            'Project cost ceiling of ₹50 Lakh for manufacturing and ₹20 Lakh for service units',
            'Mandatory 5 to 10 days Entrepreneurship Development Programme (EDP) training',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: ['Unemployed', 'Self-employed', 'Artisan', 'Youth'],
            education: ['Class 8 passed (for projects above ₹10L)'],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isRural: true,
        },
        requiredDocuments: [
            'Aadhaar Card & PAN',
            'Project Report (DPR)',
            'Educational Qualification Certificate',
            'Caste / Rural Area Certificate',
        ],
        applicationProcess: [
            'Apply online via kviconline.gov.in/pmegpeportal',
            'District Level Task Force Committee (DLTFC) scrutinizes project proposal',
            'Forwarded to financing bank for loan sanction and subsidy escrow release',
        ],
        officialUrl: 'https://www.kviconline.gov.in/pmegpeportal',
        tags: ['pmegp', 'capital subsidy', 'manufacturing grant', 'kvic subsidy'],
    },

    // ================= 5. EDUCATION & SKILL DEVELOPMENT =================
    {
        name: 'National Scholarship Portal (NSP) - Pre & Post Matric Scholarships',
        description: 'Single-window electronic scholarship disbursement system for students from SC, ST, OBC, Minority, and EWS backgrounds.',
        categoryTag: 'Education',
        ministry: 'Ministry of Social Justice & Ministry of Education',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '100% Tuition Fee Reimbursement + Monthly Maintenance Allowance',
        helpline: '0120-6619540',
        benefits: [
            'Direct credit of tuition fees directly to educational institution',
            'Monthly maintenance stipend up to ₹1,200/month for hostellers and day scholars',
            'Book allowances and disability transport allowances',
        ],
        eligibility: {
            ageMin: 5,
            ageMax: 32,
            incomeMax: 250000,
            gender: 'All',
            occupation: ['Student'],
            education: ['Class 1 to 12', 'Diploma', 'Undergraduate', 'Postgraduate', 'PhD'],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isStudent: true,
        },
        requiredDocuments: [
            'Aadhaar Card',
            'Income Certificate issued by competent Revenue Authority (Tahsildar)',
            'Caste Certificate (SC/ST/OBC)',
            'Previous year marksheet / Bonafide Student Certificate',
            'Student Bank Passbook',
        ],
        applicationProcess: [
            'Register on scholarships.gov.in with OTR (One Time Registration)',
            'Select matching scheme (Post-Matric / Top Class Education / Merit-cum-Means)',
            'Institute Nodal Officer (INO) and District Nodal Officer (DNO) verify records',
            'Direct DBT disbursement through PFMS pipeline',
        ],
        officialUrl: 'https://scholarships.gov.in',
        tags: ['scholarship', 'education', 'nsp', 'student fees', 'college grant'],
    },
    {
        name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)',
        description: 'Skill development initiative providing free industry-relevant training, digital literacy, Industry 4.0 skills, and NSDC certification with stipend rewards.',
        categoryTag: 'Education',
        ministry: 'Ministry of Skill Development and Entrepreneurship (MSDE)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '100% Free Skill Certification + ₹8,000 Post-Placement Reward',
        helpline: '088000-55555',
        benefits: [
            'Short Term Training (STT) and Recognition of Prior Learning (RPL)',
            'Modern courses in AI, Robotics, Drone Technology, Coding, and Healthcare',
            'Recognized National Skills Qualification Framework (NSQF) Certificate',
            'Placement assistance with corporate partners across India',
        ],
        eligibility: {
            ageMin: 15,
            ageMax: 45,
            incomeMax: null,
            gender: 'All',
            occupation: ['Unemployed', 'Student', 'Dropout', 'Job Seeker'],
            education: ['Class 10', 'Class 12', 'Graduate', 'Diploma'],
            category: [],
        },
        requiredDocuments: ['Aadhaar Card', 'Bank Account Passbook', 'Highest Educational Marksheet'],
        applicationProcess: [
            'Search courses on skillindiadigital.gov.in or visit nearest PMKK training center',
            'Enroll in chosen skill batch (duration 200 - 600 hours)',
            'Complete assessment exam and receive Govt NSDC Certificate',
        ],
        officialUrl: 'https://www.pmkvyofficial.org',
        tags: ['pmkvy', 'skill development', 'nsdc certificate', 'free job training'],
    },
    {
        name: 'AICTE Pragati Scholarship for Girl Students',
        description: 'Financial support of ₹50,000 per year to girl students admitted to technical diploma or degree courses in AICTE-approved institutions.',
        categoryTag: 'Education',
        ministry: 'All India Council for Technical Education (AICTE)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '₹50,000 per annum for tuition fees and books',
        helpline: '011-29581333',
        benefits: [
            'Direct grant of ₹50,000 for each year of course study (up to 4 years)',
            'Up to 2 girl children per family eligible',
            'No deduction for hostel or living cost expenditures',
        ],
        eligibility: {
            ageMin: 16,
            ageMax: 26,
            incomeMax: 800000,
            gender: 'Female',
            occupation: ['Student'],
            education: ['B.Tech / B.E.', 'Polytechnic Diploma', 'Engineering'],
            category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
            isStudent: true,
        },
        requiredDocuments: [
            'Class 10 & 12 Marksheets',
            'Centralized Admission Seat Allotment Letter',
            'Annual Family Income Certificate (< 8 Lakh)',
            'Aadhaar seeded bank details',
        ],
        applicationProcess: [
            'Apply on National Scholarship Portal (scholarships.gov.in) under AICTE Scheme tab',
            'Institution verifies academic admission credentials online',
            'Direct PFMS fund transfer to candidate bank account',
        ],
        officialUrl: 'https://www.aicte-india.org/schemes/students-development-schemes/Pragati',
        tags: ['girls scholarship', 'aicte', 'pragati', 'engineering scholarship'],
    },

    // ================= 6. WOMEN & CHILD WELFARE =================
    {
        name: 'Sukanya Samriddhi Yojana (SSY)',
        description: 'High-interest tax-exempt government savings scheme for girl child with guaranteed sovereign backing and 8.2% annual compounded interest.',
        categoryTag: 'Women & Child',
        ministry: 'Ministry of Finance & Ministry of Women and Child Development',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '8.2% Tax-Free Interest + Triple EEE Tax Exemption',
        helpline: '1800-266-6868',
        benefits: [
            'Highest sovereign interest rate among small savings instruments (8.2%)',
            'Triple Tax Exemption under Section 80C (Investment, Interest, Maturity)',
            'Partial withdrawal permitted at age 18 for higher education',
        ],
        eligibility: {
            ageMin: 0,
            ageMax: 10,
            incomeMax: null,
            gender: 'Female',
            occupation: [],
            education: [],
            category: [],
        },
        requiredDocuments: [
            'Girl Child Birth Certificate',
            'Parent / Legal Guardian Aadhaar & PAN Card',
            'Address Proof & Passport size photographs',
        ],
        applicationProcess: [
            'Visit any designated Post Office branch or authorized public/private commercial bank',
            'Fill Sukanya Samriddhi account opening form (Form-1)',
            'Deposit initial opening amount (minimum ₹250)',
            'Receive SSY passbook with recorded deposit milestones',
        ],
        officialUrl: 'https://www.indiapost.gov.in',
        tags: ['girl child', 'sukanya samriddhi', 'savings', 'tax free', 'education fund'],
    },
    {
        name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
        description: 'Direct Benefit Transfer maternity benefit scheme providing ₹5,000 - ₹6,000 cash incentive for pregnant and lactating mothers for health and wage compensation.',
        categoryTag: 'Women & Child',
        ministry: 'Ministry of Women and Child Development',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '₹5,000 for 1st Child + ₹6,000 for 2nd Girl Child in DBT',
        helpline: '1098 / 011-23382393',
        benefits: [
            'Compensates for wage loss during pregnancy and childbirth',
            'Promotes institutional delivery, early registration, and child immunization',
            'Transferred in structured installments linked to prenatal and postnatal milestones',
        ],
        eligibility: {
            ageMin: 19,
            ageMax: 45,
            incomeMax: 800000,
            gender: 'Female',
            occupation: ['Pregnant Women', 'Lactating Mother'],
            education: [],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isBelowPovertyLine: true,
        },
        requiredDocuments: [
            'Mother and Child Protection (MCP) Card',
            'Aadhaar Card of Mother and Husband',
            'Bank Account Passbook of Mother',
        ],
        applicationProcess: [
            'Register at nearest Anganwadi Centre (AWC) or approved health facility',
            'Complete antenatal check-up (ANC) within 6 months of pregnancy',
            'Submit Child Birth & Immunization records for final installment',
        ],
        officialUrl: 'https://pmmvy.wcd.gov.in',
        tags: ['pmmvy', 'maternity benefit', 'pregnancy aid', 'anganwadi'],
    },
    {
        name: 'One Stop Centre (Sakhi Scheme)',
        description: 'Integrated emergency shelter, medical aid, legal aid, police assistance, and psycho-social counseling for women affected by violence or domestic abuse under one roof.',
        categoryTag: 'Women & Child',
        ministry: 'Ministry of Women and Child Development',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '100% Free Legal, Medical & Psychological Crisis Support',
        helpline: '181 (Women Helpline) / 112 (Emergency)',
        benefits: [
            'Immediate temporary shelter up to 5 days with food and toiletries',
            'Free forensic and medical examination by medical officers',
            '24/7 dedicated legal advocate support and police FIR facilitation',
            'Psychological trauma counseling and rehabilitation assistance',
        ],
        eligibility: {
            ageMin: 0,
            ageMax: null,
            incomeMax: null,
            gender: 'Female',
            occupation: [],
            education: [],
            category: [],
        },
        requiredDocuments: ['Any Available ID (Not mandatory for emergency rescue)'],
        applicationProcess: [
            'Call 181 Women Helpline or walk into nearest District Hospital Sakhi Centre',
            'Center case manager coordinates immediate medical treatment and police reporting',
            'Legal aid counsel is assigned for Protection Orders under Domestic Violence Act',
        ],
        officialUrl: 'https://wcd.nic.in/schemes/one-stop-centre-scheme-1',
        tags: ['sakhi', 'women safety', 'domestic violence', 'emergency legal help', 'one stop centre'],
    },

    // ================= 7. HOUSING & URBAN DEVELOPMENT =================
    {
        name: 'Pradhan Mantri Awas Yojana (PMAY) - Housing for All',
        description: 'Provides pucca houses with basic amenities (water, electricity, toilet) or interest subsidy up to ₹2.67 Lakh on home loans.',
        categoryTag: 'Housing & Urban',
        ministry: 'Ministry of Housing and Urban Affairs & Ministry of Rural Development',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Direct Construction Grant ₹1.2 - 2.5 Lakh / ₹2.67 Lakh Interest Subsidy',
        helpline: '1800-11-3377 / 1800-11-6163',
        benefits: [
            'Financial grant of ₹1,20,000 in plains and ₹1,30,000 in hilly states for rural houses',
            'Credit Linked Subsidy Scheme (CLSS) up to 6.5% interest concession for urban buyers',
            'Mandatory female co-ownership empowering women in household title deeds',
        ],
        eligibility: {
            ageMin: 21,
            ageMax: 70,
            incomeMax: 600000,
            gender: 'All',
            occupation: [],
            education: [],
            category: ['SC', 'ST', 'OBC', 'EWS', 'LIG'],
            isBelowPovertyLine: true,
        },
        requiredDocuments: [
            'Aadhaar Card of all family members',
            'Income Certificate & Affidavit of not owning a pucca house in India',
            'Land Title Proof / Gram Panchayat No Objection Certificate',
            'Bank Account with Aadhaar linkage',
        ],
        applicationProcess: [
            'Apply online on pmaymis.gov.in or through Gram Panchayat Awas+ portal',
            'Geo-tagging of existing kuccha house / proposed site',
            'Approval by District Collector / ULB Committee',
            'Phased fund release mapped to foundation, lintel, and roof completion stages',
        ],
        officialUrl: 'https://pmaymis.gov.in',
        tags: ['pmay', 'housing', 'pucca house', 'home subsidy', 'gramin awas'],
    },
    {
        name: 'Swachh Bharat Mission (Gramin & Urban) - Individual Household Latrine (IHHL)',
        description: 'Direct financial assistance of ₹12,000 per beneficiary for constructing modern sanitary toilets to ensure 100% open defecation free (ODF) communities.',
        categoryTag: 'Housing & Urban',
        ministry: 'Ministry of Jal Shakti & Ministry of Housing and Urban Affairs',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '₹12,000 Cash Grant per Beneficiary Household',
        helpline: '1800-1800-404',
        benefits: [
            'Direct transfer of ₹12,000 incentive into beneficiary bank account',
            'Improves household dignity, women safety, and community hygiene',
            'Geo-tagged photo verification ensuring fast clearance',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            gender: 'All',
            occupation: [],
            education: [],
            category: ['SC', 'ST', 'OBC', 'General', 'EWS'],
            isBelowPovertyLine: true,
            isRural: true,
        },
        requiredDocuments: ['Aadhaar Card', 'Bank Passbook copy', 'Photograph of applicant in front of toilet site'],
        applicationProcess: [
            'Register on sbm.gov.in portal or via Gram Panchayat Secretary',
            'Upload bank details and photo of proposed construction spot',
            'Field inspection by block coordinator followed by DBT credit',
        ],
        officialUrl: 'https://swachhbharatmission.gov.in',
        tags: ['toilet subsidy', 'swachh bharat', 'ihhl', 'sanitation grant'],
    },

    // ================= 8. SENIOR CITIZENS & SOCIAL SECURITY =================
    {
        name: 'Rashtriya Vayoshri Yojana (RVY)',
        description: 'Provides physical aids and assisted-living devices for Senior Citizens belonging to BPL category suffering from age-related disabilities or infirmities.',
        categoryTag: 'Senior Citizens',
        ministry: 'Ministry of Social Justice and Empowerment',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '100% Free Assisted Living Devices (Wheelchairs, Hearing Aids, Spectacles)',
        helpline: '14567 (Elder Line National Helpline)',
        benefits: [
            'Free distribution of motorized wheelchairs, walking sticks, crutches',
            'High-grade digital hearing aids and spectacles',
            'Artificial dentures and cervical collars provided without charge',
        ],
        eligibility: {
            ageMin: 60,
            ageMax: null,
            incomeMax: 200000,
            gender: 'All',
            occupation: ['Senior Citizen', 'Retired'],
            education: [],
            category: [],
            isBelowPovertyLine: true,
        },
        requiredDocuments: [
            'Proof of Age (Senior Citizen Card, Aadhaar, Voter ID indicating 60+ years)',
            'BPL Card / Income Certificate from Revenue Authority',
            'Certificate of Disability / Medical Assessment from Government Doctor',
        ],
        applicationProcess: [
            'Registration at district assessment camp organized by ALIMCO / District Social Welfare Officer',
            'Clinical evaluation by medical specialists for device sizing and prescription',
            'Free distribution at official ceremonial camp with manufacturer warranty',
        ],
        officialUrl: 'https://socialjustice.gov.in',
        tags: ['senior citizens', 'wheelchair', 'hearing aid', 'elderly aid', 'alimco'],
    },
    {
        name: 'Atal Pension Yojana (APY) - Guaranteed Social Security',
        description: 'Universal pension scheme for all unorganized sector workers with guaranteed minimum monthly pension of ₹1,000 to ₹5,000 after age 60.',
        categoryTag: 'Senior Citizens',
        ministry: 'Pension Fund Regulatory and Development Authority (PFRDA)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Guaranteed Lifetime Pension ₹1,000 - ₹5,000 / month',
        helpline: '1800-110-069',
        benefits: [
            'Guaranteed monthly pension backed by Government of India',
            'Same pension paid to spouse upon subscriber demise',
            'Full accumulated pension corpus returned to legal nominees',
            'Tax benefit under Section 80CCD(1B)',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: 40,
            incomeMax: null,
            gender: 'All',
            occupation: ['Unorganized worker', 'Self-employed', 'Farmer', 'Gig Worker', 'Labourer'],
            education: [],
            category: [],
        },
        requiredDocuments: [
            'Aadhaar Card',
            'Savings Bank Account with Auto-Debit facility enabled',
            'Mobile Number',
        ],
        applicationProcess: [
            'Visit your bank branch or log into Net Banking / Mobile Banking app',
            'Select APY registration and desired pension tier (₹1,000 to ₹5,000)',
            'Specify nominee details and authorize monthly auto-debit',
            'Receive permanent PRAN card confirmation via SMS',
        ],
        officialUrl: 'https://www.npscra.nsdl.co.in',
        tags: ['pension', 'atal pension', 'social security', 'retirement', 'monthly pension'],
    },
    {
        name: 'Divyangjan Swavalamban Yojana (National Handicapped Finance Dev)',
        description: 'Concessional loans with subsidized interest rates up to ₹50 Lakh for Persons with Disabilities (PwD) for higher education, self-employment, and assistive tech.',
        categoryTag: 'Senior Citizens',
        ministry: 'Department of Empowerment of Persons with Disabilities',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Concessional Loans up to ₹50,00,000 at 5% - 8% Interest',
        helpline: '0129-2226910',
        benefits: [
            'Low interest rates starting at 5% per annum for small ventures',
            '1% interest rebate for women with disabilities',
            'Loans for purchasing retrofitted vehicles, computer equipment, Braille tech',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: 65,
            incomeMax: 500000,
            gender: 'All',
            occupation: ['Self-employed', 'Student', 'Entrepreneur'],
            education: [],
            category: [],
            isDisability: true,
        },
        requiredDocuments: [
            'Unique Disability ID (UDID) Card or Disability Certificate (40%+ disability)',
            'Aadhaar Card & Proof of Age',
            'Business or Educational Project Proposal',
        ],
        applicationProcess: [
            'Apply online via nhfdc.nic.in or through State Channelising Agencies (SCAs) / PNB / Bank of Baroda',
            'Submit project proposal along with UDID card',
            'SCA scrutinizes application and sanctions concessional term loan',
        ],
        officialUrl: 'https://nhfdc.nic.in',
        tags: ['disability', 'divyangjan', 'udid', 'pwd loan', 'concessional credit'],
    },
    {
        name: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
        description: 'Monthly direct cash pension to destitute elderly citizens below the poverty line to ensure living dignity and healthcare autonomy.',
        categoryTag: 'Senior Citizens',
        ministry: 'Ministry of Rural Development (NSAP)',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Monthly Pension ₹1,000 - ₹2,500 (with State Top-Up)',
        helpline: '1800-180-1551',
        benefits: [
            'Unconditional monthly pension credited via Direct Benefit Transfer',
            'Additional state government top-up (e.g. ₹2,016 in Telangana, ₹2,500 in AP)',
            'Automatic transition to higher slab upon reaching 80 years',
        ],
        eligibility: {
            ageMin: 60,
            ageMax: null,
            incomeMax: 150000,
            gender: 'All',
            occupation: ['Senior Citizen', 'Unemployed'],
            education: [],
            category: [],
            isBelowPovertyLine: true,
        },
        requiredDocuments: ['Aadhaar Card', 'BPL Card / SECC Data', 'Bank Passbook', 'Age Proof'],
        applicationProcess: [
            'Submit application to Gram Panchayat / Municipal Office or online on nsap.nic.in',
            'Field verification by Panchayat Secretary / Revenue Inspector',
            'Sanction order issued with monthly auto-credit to bank account',
        ],
        officialUrl: 'https://nsap.nic.in',
        tags: ['old age pension', 'ignops', 'senior citizen monthly grant', 'nsap'],
    },

    // ================= 9. MINORITY & TRIBAL WELFARE =================
    {
        name: 'PM VIKAS (Pradhan Mantri Virasat Ka Samvardhan)',
        description: 'Integrated socio-economic empowerment scheme for traditional artisans, craftsmen, and minority communities with credit linkages, modern tools, and market access.',
        categoryTag: 'Minority & Tribal',
        ministry: 'Ministry of Minority Affairs',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '100% Free Artisan Toolkits + Up to ₹10 Lakh Concessional Credit',
        helpline: '1800-11-2001',
        benefits: [
            'Skill upgradation and modern design training with master artisans',
            'Distribution of specialized digital and mechanical equipment toolkits',
            'National e-Commerce onboarding on GeM and Hunar Haat exhibitions',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: null,
            incomeMax: 300000,
            gender: 'All',
            occupation: ['Artisan', 'Craftsman', 'Weaver', 'Sculptor'],
            education: [],
            category: ['SC', 'ST', 'OBC', 'EWS'],
        },
        requiredDocuments: ['Artisan Pehchan Card / Aadhaar', 'Community Minority / Caste Certificate', 'Bank Passbook'],
        applicationProcess: [
            'Register on PM VIKAS portal or through District Industries Centre (DIC)',
            'Skill assessment and issue of modernization kit',
            'Credit linkage through NMDFC partner financial institutions',
        ],
        officialUrl: 'https://minorityaffairs.gov.in',
        tags: ['minority', 'artisan', 'pm vikas', 'craftsman grant', 'hunar haat'],
    },
    {
        name: 'Eklavya Model Residential School (EMRS) Free Education',
        description: '100% free high-quality CBSE residential schooling, boarding, uniform, textbooks, and coaching for Scheduled Tribe (ST) students in remote tribal areas.',
        categoryTag: 'Minority & Tribal',
        ministry: 'Ministry of Tribal Affairs',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: '100% Free Quality Residential Schooling, Boarding & NEET/JEE Coaching',
        helpline: '011-23381652',
        benefits: [
            'Completely free education from Class 6 to 12 in state-of-the-art CBSE campuses',
            'Free nutritious boarding, lodging, uniform, books, and medical care',
            'Specialized coaching for competitive entrance exams (NEET, JEE, CLAT, CUET)',
        ],
        eligibility: {
            ageMin: 10,
            ageMax: 18,
            incomeMax: null,
            gender: 'All',
            occupation: ['Student'],
            education: ['Class 5 passed'],
            category: ['ST'],
            isStudent: true,
            isRural: true,
        },
        requiredDocuments: ['ST Caste Certificate', 'Class 5 Marksheet / Bonafide', 'Aadhaar Card', 'Birth Certificate'],
        applicationProcess: [
            'Apply online for EMRS Selection Test (EMRSST) at emrs.tribal.gov.in',
            'Appear for district entrance exam testing aptitude and language',
            'Merit-based admission allotment in nearest residential campus',
        ],
        officialUrl: 'https://emrs.tribal.gov.in',
        tags: ['tribal education', 'st scholarship', 'emrs', 'free residential school'],
    },

    // ================= 10. YOUTH & EMPLOYMENT =================
    {
        name: 'e-Shram: National Database of Unorganized Workers',
        description: 'Universal digital identity and social security card providing ₹2 Lakh accidental insurance (under PMSBY) and seamless welfare scheme portability for gig and migrant workers.',
        categoryTag: 'Youth & Employment',
        ministry: 'Ministry of Labour and Employment',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Free Universal UAN Card + ₹2,00,000 Accidental Insurance Cover',
        helpline: '14434 (e-Shram National Helpdesk)',
        benefits: [
            'Unique 12-digit Universal Account Number (UAN) valid across all states',
            '₹2 Lakh in case of accidental death/permanent disability, ₹1 Lakh for partial disability',
            'Direct gateway for emergency cash relief and migrant transit benefits',
        ],
        eligibility: {
            ageMin: 16,
            ageMax: 59,
            incomeMax: null,
            gender: 'All',
            occupation: ['Construction Worker', 'Gig Driver', 'Domestic Maid', 'Agricultural Laborer', 'Street Hawker'],
            education: [],
            category: [],
        },
        requiredDocuments: ['Aadhaar Card', 'Aadhaar linked active Mobile Number', 'Bank Account details'],
        applicationProcess: [
            'Self-register on eshram.gov.in or visit nearest CSC / State Seva Kendra',
            'Enter Aadhaar OTP and declare occupation / skill classification',
            'Download and print laminated permanent e-Shram Card with QR code',
        ],
        officialUrl: 'https://eshram.gov.in',
        tags: ['eshram', 'unorganized worker', 'gig worker', 'accidental insurance', 'uan card'],
    },
    {
        name: 'National Career Service (NCS) - Employment & Apprenticeship Portal',
        description: 'All-in-one national digital platform matching job seekers with government vacancies, private corporate recruiters, free career counseling, and skill training.',
        categoryTag: 'Youth & Employment',
        ministry: 'Ministry of Labour and Employment',
        state: 'All India',
        isCentralScheme: true,
        financialBenefit: 'Free Job Matching, Aptitude Testing & Direct Rozgar Mela Access',
        helpline: '1800-425-1514',
        benefits: [
            'Direct access to over 5,00,000+ active job openings across India',
            'Free psychometric career counseling sessions with certified counselors',
            'Direct passes to monthly National Rozgar Melas and Campus Placement Drives',
        ],
        eligibility: {
            ageMin: 18,
            ageMax: 50,
            incomeMax: null,
            gender: 'All',
            occupation: ['Unemployed', 'Job Seeker', 'Graduate', 'Diploma Holder'],
            education: ['Class 10', 'Class 12', 'Diploma', 'Graduate', 'Postgraduate'],
            category: [],
        },
        requiredDocuments: ['Aadhaar / Voter ID', 'Resume / CV', 'Educational Certificates'],
        applicationProcess: [
            'Register on ncs.gov.in as Jobseeker with Job Profile & Skill Set',
            'Verify mobile number and receive NCS Jobseeker ID',
            'Apply directly for verified private and government job postings',
        ],
        officialUrl: 'https://www.ncs.gov.in',
        tags: ['job portal', 'ncs', 'employment', 'rozgar mela', 'career counseling'],
    },
];

const seedSchemes = async () => {
    try {
        const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/legalease';
        await mongoose.connect(uri);
        console.log('✅ Connected to MongoDB at:', uri);

        // Clear existing schemes
        await Scheme.deleteMany({});
        console.log('🗑️ Cleared existing schemes');

        // Insert comprehensive schemes
        const inserted = await Scheme.insertMany(schemes);
        console.log(`🚀 Successfully inserted ${inserted.length} comprehensive Legal Aid & Welfare Schemes across 10 categories!`);

        process.exit(0);
    } catch (error) {
        console.error('❌ Error seeding schemes:', error);
        process.exit(1);
    }
};

seedSchemes();